let query = {
  allPlainte:
    "select `p`.`IDplainte` AS `IDplainte`,`p`.`detailsDescription` AS `detailsDescription`,`p`.`observation` AS `observation`,`p`.`numeroClt` AS `numeroClt`,`p`.`dhReception` AS `dhReception`,`p`.`dhSignalisation` AS `dhSignalisation`,`p`.`dhCloture` AS `dhCloture`,`p`.`dhTraitement` AS `dhTraitement`,`p`.`dhTransmission` AS `dhTransmission`,`p`.`dhRetour` AS `dhRetour`,`p`.`dhEcheance` AS `dhEcheance`,`p`.`tempsTraitement` AS `tempsTraitement`,`p`.`tempsResolution` AS `tempsResolution`,`p`.`tempsAttente` AS `tempsAttente`,`p`.`tempsHorsAIC` AS `tempsHorsAIC`,`p`.`oceane` AS `oceane`,`p`.`etatPlainte` AS `etatPlainte`,`p`.`statut` AS `statut`,`p`.`priorite` AS `priorite`,`p`.`etatEcheance` AS `etatEcheance`,`p`.`commune` AS `commune`,`p`.`quartier` AS `quartier`,`p`.`numCase` AS `numCase`,`p`.`agent` AS `agent`,`canal`.`libelle` AS `canal`,`partenaire`.`libelle` AS `partenaire`,`description`.`libelle` AS `description`,`domaine`.`libelle` AS `domaine`,`nature`.`libelle` AS `nature`,`origine`.`libelle` AS `origine`,`porteur`.`libelle` AS `porteur`,`suborigine`.`libelle` AS `suborigine` from ((((((((`plainte` `p` left join `canal` on(`p`.`idCanal` = `canal`.`id`)) left join `partenaire` on(`p`.`idPartenaire` = `partenaire`.`id`)) left join `description` on(`p`.`idDescription` = `description`.`id`)) left join `domaine` on(`p`.`idDomaine` = `domaine`.`id`)) left join `nature` on(`p`.`idNature` = `nature`.`id`)) left join `origine` on(`p`.`idOrigine` = `origine`.`id`)) left join `porteur` on(`p`.`idPorteur` = `porteur`.`id`)) left join `suborigine` on(`p`.`idSubOrigine` = `suborigine`.`id`));",
  allPlainteOngoing:
  "select `p`.`IDplainte` AS `IDplainte`,`p`.`detailsDescription` AS `detailsDescription`,`p`.`observation` AS `observation`,`p`.`numeroClt` AS `numeroClt`,`p`.`dhReception` AS `dhReception`,`p`.`dhSignalisation` AS `dhSignalisation`,`p`.`dhCloture` AS `dhCloture`,`p`.`dhTraitement` AS `dhTraitement`,`p`.`dhTransmission` AS `dhTransmission`,`p`.`dhRetour` AS `dhRetour`,`p`.`dhEcheance` AS `dhEcheance`,`p`.`tempsTraitement` AS `tempsTraitement`,`p`.`tempsResolution` AS `tempsResolution`,`p`.`tempsAttente` AS `tempsAttente`,`p`.`tempsHorsAIC` AS `tempsHorsAIC`,`p`.`oceane` AS `oceane`,`p`.`etatPlainte` AS `etatPlainte`,`p`.`statut` AS `statut`,`p`.`priorite` AS `priorite`,`p`.`etatEcheance` AS `etatEcheance`,`p`.`commune` AS `commune`,`p`.`quartier` AS `quartier`,`p`.`numCase` AS `numCase`,`p`.`agent` AS `agent`,`canal`.`libelle` AS `canal`,`partenaire`.`libelle` AS `partenaire`,`description`.`libelle` AS `description`,`domaine`.`libelle` AS `domaine`,`nature`.`libelle` AS `nature`,`origine`.`libelle` AS `origine`,`porteur`.`libelle` AS `porteur`,`suborigine`.`libelle` AS `suborigine` from ((((((((`plainte` `p` left join `canal` on(`p`.`idCanal` = `canal`.`id`)) left join `partenaire` on(`p`.`idPartenaire` = `partenaire`.`id`)) left join `description` on(`p`.`idDescription` = `description`.`id`)) left join `domaine` on(`p`.`idDomaine` = `domaine`.`id`)) left join `nature` on(`p`.`idNature` = `nature`.`id`)) left join `origine` on(`p`.`idOrigine` = `origine`.`id`)) left join `porteur` on(`p`.`idPorteur` = `porteur`.`id`)) left join `suborigine` on(`p`.`idSubOrigine` = `suborigine`.`id`)) WHERE `p`.`statut` = 'En Cours';"
    
};

module.exports = query;


